### ISSUE TITLE
Declare equivalence between (pending) CategoryCode and CredentialAlignmentObject

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#291]
There is a pending class in schema.org called [`schema:CategoryCode`](https://github.com/schemaorg/schemaorg/issues/894) that has equivalencies to our [`ceterms:CredentialAlignmentObject`](http://schema.org/AlignmentObject) (that refines the [`schema:AlignmentObject`](https://schema.org/AlignmentObject)). The `schema:CategoryCode` is a renaming of the already-pending `EnumerationValue` proposal that we have been closely monitoring. When `schema:CategoryCode` is approved, we need to formally declare the equivalency in our definition of  [`ceterms:CredentialAlignmentObject`](http://schema.org/AlignmentObject). 

It is somewhat unfortunate (but the way of things) that the incubation timing on the schema.org proposal here have taken so long since refinements of [`schema:AlignmentObject`](https://schema.org/AlignmentObject) are a kludgy way of solving our need to reference concepts in concept schemes.

Below is an encoding using `CategoryCode` adapted from an example by Richard Wallis (all criticisms of using URL in the CTDL context still stand):

```
{ "@context": "http://schema.org/",
"@type": "Person",
"name": "John Doe",
"honorificPrefix": "Dr",
"sameAs": "https://en.wikipedia.org/wiki/John_Doe",
"naics" : ["xx", "xx"],
"isicV4": ["xx", "xx"],  
"occupation": [ 
    { 
      "@type": "CategoryCode",
      "name": "Family and General Practitioners",
      "codeValue": "29-1062.00",
      "description": "Physicians who diagnose, treat, and help prevent diseases and injuries...",
      "inCodeSet": "https://www.onetonline.org/",
      "url":"https://www.onetonline.org/link/summary/29-1062.00"
    },
    { "@type": "CategoryCode",
      "name": "general practitioner",
      "codeValue": "Q6500773",
      "description": "type of medical doctor specialising as a generalist, usually working in primary care setting...",
      "inCodeSet": "https://www.wikidata.org/",
      "url":"https://www.wikidata.org/wiki/Q6500773)"
    }
  ]
}
```

**Comment by jvandriel** [comment]
You might consider updating your example to include ```Profession```, as is being discussed in #1410, to something like this:
```
"occupation":
{
  "@type":"Profession",
  "occupationalCategory":
  {
    "@type":"CategoryCode",
    "name":"Explosives Workers, Ordnance Handling Experts, and Blasters",
    "codeValue":"47-5031.00",
    "inCodeSet":"https://www.onetcenter.org/taxonomy/2010/list.html"
      }
    }
```

**Comment by stuartasutton** [comment]
@jkitchensSIUC, @philbarker, @siuc-nate & @cwd-mparsons: 

I want to return to this issue since there is a **high probability** of an update to the pending schema.org/CategoryCode (see discussion at https://github.com/schemaorg/schemaorg/issues/1711). The change bubbling up is modification of the current pending definition and entity and property names:

> **DefinedTerm** (pending [CategoryCode](http://pending.schema.org/CategoryCode))
**DefinedTermSet**  (pending [CategoryCodeSet](http://pending.schema.org/CategoryCodeSet)) 
**inDefinedTermSet** (pending [inCodeSet](http://pending.schema.org/inCodeSet))
**termCode** (pending [codeValue](http://pending.schema.org/codeValue))
**hasDefinedTerm** (pending [hasCategoryCode](http://pending.schema.org/hasCategoryCode))

The currently proposed definition of `DefinedTerm` is:

>"a word, name, acronym, phrase, etc. with a formal definition. Often used in the context of category or subject classification, glossaries or dictionaries, product or creative work types, etc. Use the name property for the term being defined, use termCode if the term has an alpha-numeric code allocated, use description to provide the definition of the term."

This is important to CE because throughout the CTDL description language, we have used our sub-type of [schema.org/AlignmentObject](http://schema.org/AlignmentObject) ([ceterms:CredentialAlignmentObject](http://credreg.net/ctdl/terms#CredentialAlignmentObject)) for the exact purpose set out in the proposed revised definition for `DefinedTerm`.

The use of the `CredentialAlignmentObject` in the CTDL has not been without controversy since it pushes the boundaries of the intended use(s) of the `schema.org/AlignmentObject`. The *primary* function of the `schema.org/AlignmentObject` is to provide specificity to an otherwise general property defining the nature of the alignment (see [`educationalAlignment`](http://schema.org/educationalAlignment)) in the following example) and *secondarily* to minimally describe a framework node being referenced:

>Learning Resource==educationalAlignment==>AlignmentObject
AlignmentObject==alignmentType==>"Teaches"

The *secondary* purpose --describing a framework node in the form of a concept or competency-- will be preempted in schema.org practice by the pending (and updated) [`schema.org/DefinedTerm`](http://pending.schema.org/CategoryCode). The CTDL does **not** use the `CredentialAlignmentObject` for its *primary* purpose but solely for its `secondary` purpose and will be out of sync with schema.org when `DefinedTerm` moves from pending to live.

**Comment by siuc-nate** [comment]
Once frameworks/competencies are available to be linked to, alignment object will do so - that should mean it's fulfilling both of its purposes.  Similarly, we also use it to point to vocabularies (primary purpose) and indicate data from the targeted vocabulary term (secondary purpose).  

And, since we do the competency alignments via specialized properties that render the alignmentType sort of unnecessary in competency-related cases (at least the cases we've addressed so far), I don't think we're as far off-base from the purpose of AlignmentObject as your concern details. Nonetheless you make interesting points about CategoryCode and the related properties. Would that have more relevance to our controlled vocabularies?

**Comment by philbarker** [comment]
@stuartasutton Don't the added properties of the CredentialAlignmentObject, e.g. ceterms:alignmentDate fall within the generalised idea of the primary purpose?

I would phrase the issue slightly less starkly. Once DefinedTerm is in schema.org, if it is adopted by CTDL, and given that information about the alignmentType is conveyed by the CTDL predicates, then there would be no need to use AlignmentObjects unless one needed to say something else about the alignment.

BTW, I think the AlignmentObject might be like a balloon: if you don't push against the  boundaries of its intended use(s) it will collapse under external pressures.

**Comment by stuartasutton** [comment]
Nate, you missed the point of the "primary" purpose. It isn't that it links. What I call the primary purpose is to more definitively state the nature of the relationship (property) that points at the alignmentObject. 

In the LRMI work on learning resources, there was only ONE property that pointed from a `CreativeWork` to an `AlignmentObject`--`educationalAlignment`. Then the `alignmentType` property of `AlignmentObject` identifies what  `educationalAlignment` ***really means***...e.g., "teaches", "assesses" etc. So the primary function (in my opinion) is to  identify what the alignment really is. In CTDL, we point at instances of `CredentialAlignmentObject` with properties that ***really mean what we intend***...thus my pushback on duplicative use of the `alignmentType` property. So, no, we don't use `CredentialAlignmentObject` to identify our actual intention with regard to the property that points at it; we use it ***solely*** to describe (and, when luck) point to the framework. That is EXACTLY what the `DefinedTerm` does.

**Comment by stuartasutton** [comment]
Phil states: "Once DefinedTerm is in schema.org, if it is adopted by CTDL, and given that information about the alignmentType is conveyed by the CTDL predicates, then there would be no need to use AlignmentObjects unless one needed to say something else about the alignment."

YES! 

CredentialAlignmentType would be appropriate if you wanted to say that a resource assesses a particular Competency with a weight of 80% (whatever that means); in such a case, "weight" says something about (qualifies) "assessment". Same would be true if you wanted to say who claimed that "this" assesses "that". AlignmentObject would be suitable there as well because it is qualifying the relationship (property).

Credential==assesses==>

**Comment by siuc-nate** [comment]
That's what I get for attempting to respond while settling into a meeting - upon rereading your earlier post, I think it's a bit more clear.  It sounds like this would be a perfect fit for vocabulary terms, since there's no real alignment component there.  Then it's just a matter of whether or not we consider credentials to be _aligned_ to competencies vs whatever you would call their relationship to controlled vocabularies, I suppose. I do think there might be some value in the weight property and, maybe in some edge case, the alignmentType property, but I can't think of an example for the latter offhand.  

I am less fond of the idea of deprecating a whole object and replacing it with a nearly identical one, but if that's what it comes down to, I suppose we could add properties to our equivalent of CategoryCode in the future as needed.  If, however, judging by the title of this thread the only real thing being called for here is to add an assertion of `ceterms:CredentialAlignmentObject => equivalentTo => schema:CategoryCode`, that is certainly worth doing and easily accomplished.
